apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: port-number-range
  annotations:
    description: Container port range must be within <min> ... <max>
spec:
  crd:
    spec:
      names:
        kind: port-number-range
      validation:
        openAPIV3Schema:
          properties:
            min:
              type: string
            max:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package portnumberrange

        violation[{"msg": msg, "details": {}}] {
          port := input.review.object.spec.containers[_].ports[_].containerPort
          min := to_number(input.parameters.min)
          port < min
          msg := sprintf("Port number %v is too small: It must be greter than %v", [port, input.parameters.min])
        }

        violation[{"msg": msg, "details": {}}] {
          port := input.review.object.spec.containers[_].ports[_].containerPort
          max := to_number(input.parameters.max)
          port > max
          msg := sprintf("Port number %v is too large: It must be smaller than %v", [port, input.parameters.max])
        }