apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: nsnaming
spec:
  crd:
    spec:
      names:
        kind: nsnaming
      validation:
        openAPIV3Schema:
          properties:
            words:
              type: array
              minItems: 1
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package nsnaming

        violation[{"msg": msg, "details": {}}] {
          word = input.parameters.words[_]
          contains(input.review.object.metadata.name, word)
          msg := sprintf("Namespace name should not include the word '%v'", [word])
        }